vich_uploader:
    db_driver: orm

    mappings:
        profile_picture:
            uri_prefix: /images/picture
            upload_destination: '%kernel.project_dir%/public/images/picture'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
