vich_uploader:
    db_driver: orm

    mappings:
        announcement_picture:
            uri_prefix: /images/annoucement
            upload_destination: '%kernel.project_dir%/public/images/annoucement'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        
        profile_picture:
            uri_prefix: /images/profile/picture
            upload_destination: '%kernel.project_dir%/public/images/profile/picture'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        
        category_picture:
            uri_prefix: /images/category/picture
            upload_destination: '%kernel.project_dir%/public/images/category/picture'
            namer: Vich\UploaderBundle\Naming\OrignameNamer