vich_uploader:
    db_driver: orm

    mappings:
        announcement_picture:
            uri_prefix: /images/annoucement
            upload_destination: '%kernel.project_dir%/public/images/annoucement'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
